import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Login from "../components/login.component";
import Register from "../components/register.component";
import Reset from "../components/reset.component";

export default function Home() {
  const [toggle, setToggle] = useState("login");
  console.log(toggle);

  return (
    <section>
      <Head>
        <title>Demo Group Project - CSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="hero min-h-screen bg-base-200"
        style={{ backgroundImage: `url("https://placeimg.com/1000/800/arch")` }}
      >
        <div className="hero-overlay bg-opacity-70"></div>
        <div className="hero-content flex-col lg:flex-row-reverse">
          <div className="text-center lg:text-left text-white flex flex-col gap-y-4">
            <div className="flex items-center gap-x-4">
              <Image
                src="/no-user.jpg"
                alt="no user detected"
                width={80}
                height={80}
              />
              <h3 className="text-2xl font-bold bg-secondary px-4 py-2 rounded shadow">No User</h3>
            </div>
            <div>
              <h1 className="text-5xl font-bold">{toggle} now!</h1>
              <p className="py-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Consequuntur atque incidunt eaque, voluptatibus quaerat
                voluptate inventore reiciendis cumque error placeat modi
                exercitationem corrupti doloremque voluptatem tempora enim
                recusandae cum esse culpa? Commodi obcaecati beatae numquam non
                nam sint fugit animi cupiditate ipsum exercitationem, quibusdam
                incidunt temporibus fuga delectus quae quaerat cum veritatis
                natus perferendis excepturi minima porro ab ad repellendus!
                Expedita, nihil numquam amet at repudiandae voluptas optio, quod
                ipsam animi unde quos vitae laboriosam, tempore debitis error
                minus aliquid magni deleniti modi. Fugiat magni eius laboriosam
                incidunt maiores possimus distinctio saepe ratione dolor natus.
                Maxime adipisci quos vero aut?
              </p>
            </div>
          </div>
          <div className="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
            <div className="card-body">
              {toggle === "login" && <Login setToggle={setToggle} />}
              {toggle === "reset" && <Reset setToggle={setToggle} />}
              {toggle === "register" && <Register setToggle={setToggle} />}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
